# Generated by Django 6.0.3 on 2026-03-19 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterprofile',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_voters', to='elections.votingstation'),
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
